Update references from claim->statement and ledger-->append-only log
scitt-community/scitt-web pull request #45
Opened 2023-09-25 01:52 UTC by SteveLasker

This PR addresses the root `readme.md` to ensure the generic references to Statement flow when used in descriptive sentences. 
This includes
- Capitalizing `S` in `Statement` to refer to the term.
- Use of `append-only log` - should this also be capitalized `Append-only log`?

If approved, a scrub of the remaining pages will be updated.

2023-09-26 06:52 UTC, henkbirkholz requested changes

2023-09-26 06:52 UTC, henkbirkholz commented on README.md
> +SCITT is analogous to a digital, or electronic notary service (eNotary), where minimal information is written to the append-only log, counter-signing the Statement. When users notarize legal document
```suggestion
SCITT is analogous to a digital or electronic notary service (eNotary), where minimal information is written to the append-only log and an augmented counter-signature over the Statement and corresponding metadata (Receipt) is produced. When users notarize legal documents, the notary append-only log records the verified identity of the parties, referencing the legal document they are notarizing. The notary append-only log doesn't store the legal document, but does have a reference to it. 
```

2023-09-26 06:52 UTC, henkbirkholz commented on README.md
> +In SCITT, the append-only log will contain pointers to the artifact, which Statements are made, with optional pointers to any supporting evidence.
Is that found in specification text today?

2023-09-26 06:52 UTC, henkbirkholz commented on README.md
> +A SCITT instance will persist Transparent Statements to its append-only log. Any optional evidence will be persisted in associated storage.
What would be an example of 'optional evidence'?

2023-09-28 20:54 UTC, SteveLasker commented on README.md
> +In SCITT, the append-only log will contain pointers to the artifact, which Statements are made, with optional pointers to any supporting evidence.
This is just updating terminology of ledger to append-only log
Are you asking if this was copy/pasted from the spec?

2023-09-28 20:55 UTC, SteveLasker commented on README.md
> +A SCITT instance will persist Transparent Statements to its append-only log. Any optional evidence will be persisted in associated storage.
SBOM, VEX, Scan Report, and supporting document that is either in, or referenced by the COSE Envelope

2023-09-30 15:07 UTC, SteveLasker commented on README.md
> +In SCITT, the append-only log will contain pointers to the artifact, which Statements are made, with optional pointers to any supporting evidence.
@henkbirkholz, the only difference I've added was the word **optional**.  This refers to detached content. I'll make a separate PR for updating the artifact=feed and evidence = statement body. 
Any objections to merging this change for claim=statement and ledger=append-only log?

2023-10-09 17:56 UTC, OR13 commented on README.md
> +In SCITT, the append-only log will contain pointers to the artifact, which Statements are made, with optional pointers to any supporting evidence.
please merge, its an improvement.

2023-10-09 17:57 UTC, OR13 approved these changes
This PR should be merged immediately, issues should be raised for any threads that were not resolved at the time of merging.

2023-10-09 18:00 UTC, yogeshbdeshpande commented on README.md
> +SCITT is intended to store Transparent Statements for the life of the of the SCITT instance. One of the many questions that surfaces is how big will the SCITT append-only log get? What kind of data w
```suggestion
SCITT is intended to store Signed Statements for the life of the of the SCITT instance. One of the many questions that surfaces is how big will the SCITT append-only log get? What kind of data will go on the SCITT append-only log that would cause it to grow?
```

2023-10-09 18:00 UTC, yogeshbdeshpande commented on README.md
> +In SCITT, structured data is represented as a Statement. A Statement is a well-structured statement, made by a verifiable entity that may have supporting evidence.
But it may just be ok, here as the supporting evidence is the signature I suppose!

2023-10-09 18:03 UTC, yogeshbdeshpande commented on README.md
> +In SCITT, the append-only log will contain pointers to the artifact, which Statements are made, with optional pointers to any supporting evidence.
Again, we never store Transparent Statements inside log, if I understood correctly. We issue Transparent Statements by attaching Receipts to the Signed Statements!

2023-10-09 18:03 UTC, yogeshbdeshpande commented on README.md
> +A SCITT instance will persist Transparent Statements to its append-only log. Any optional evidence will be persisted in associated storage.
```suggestion
A SCITT instance will persist  Signed Statements to its append-only log. Any optional evidence will be persisted in associated storage. 
```

2023-10-09 18:37 UTC, SteveLasker commented on README.md
> +In SCITT, structured data is represented as a Statement. A Statement is a well-structured statement, made by a verifiable entity that may have supporting evidence.
The terminology used for "evidence" is another area we should clarify. I kept this PR to focus on claim--> statement.

2023-10-09 18:39 UTC, SteveLasker commented
Thanks for the reviews. I've addressed the feedback, focused on this PR, merged in the refinements from @yogeshbdeshpande on signed vs. transparent. 
Merging, pending additional updates for evidence and such.

2023-10-09 18:40 UTC, merged