SCITT Usage Examples
scitt-community/scitt-web pull request #46
Opened 2023-09-25 22:29 UTC by SteveLasker

The beginning of a collection of use cases, with examples how SCITT is used to support them.

The first one captures the binary use case, where multiple versions are concurrently supported.
How would a SCITT Feed support this scenario? 

Addresses: [Refine Definition of Feed #11](https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/11)

2023-09-25 23:11 UTC, JAG-UK commented on examples/README.md
> +To support the [SCITT Use Cases][use-cases], the follow examples are illustrated.
```suggestion
To support the [SCITT Use Cases][use-cases], the following examples are illustrated.
```

2023-09-25 23:11 UTC, JAG-UK commented on examples/feed-binary-usecase.md
> +Their software is distributed as a container images and loose binaries for Linux and Windows servers.
```suggestion
Their software is distributed as container images and loose binaries for Linux and Windows servers.
```

2023-09-25 23:11 UTC, JAG-UK commented on examples/feed-binary-usecase.md
> +They occasionally need to issue new versions of the VRF, as well as updated VEX reports.
```suggestion
They occasionally need to issue new versions of the VRF, as well as updated VEX reports, because even while the software may remain unmodified th vulnerability landscape and Rabbit Networks' understanding of it is constantly evolving.
```

2023-09-26 06:55 UTC, henkbirkholz commented on README.md
> +For more info, see: [Supply Chains]({% link supply-chain.md %})
github seems to successfully obfuscate this change for me.

2023-09-26 06:56 UTC, henkbirkholz commented on _config.yml
> +# baseurl: "/scitt-web" # use this line for local rendering and forked rendering. Revert to below before committing to the upstream project
why add this as a comment?

2023-09-26 15:52 UTC, SteveLasker commented on README.md
> +For more info, see: [Supply Chains]({% link supply-chain.md %})
Lemme take a look

2023-09-26 15:54 UTC, SteveLasker commented on _config.yml
> +# baseurl: "/scitt-web" # use this line for local rendering and forked rendering. Revert to below before committing to the upstream project
`# use this line for local rendering and forked rendering. Revert to below before committing to the upstream project`

To preview locally, uncomment the line. We could say this is tribal knowledge, or put in another doc for how to contribute, but not sure that's any different than having in the `_config.yml`. 
I'm fine either way.  It was a shortcut for not yet writing a full (`contributing-previewing.md`) file.

2023-09-28 21:16 UTC, SteveLasker commented on README.md
> +For more info, see: [Supply Chains]({% link supply-chain.md %})
fixed

2023-09-29 00:06 UTC, aj-stein-nist reviewed
Hi, I am a recent lurker in this area. I have only minor feedback about typos and such things, I hope this is helpful.

2023-09-30 15:11 UTC, SteveLasker commented
Thanks @aj-stein-nist for the feedback and your time.

2023-10-06 21:52 UTC, OR13 approved these changes

2023-10-09 14:27 UTC, henkbirkholz commented on examples/fictitious-companies.md
> +To minimize context switching when reading through SCITT Scenarios, Use Cases and Examples, a set of fictitious companies and personas are used.
```suggestion
To minimize context switching when reading through SCITT scenarios, Use Cases and Examples, a set of fictitious companies and personas are used.
```

2023-10-09 14:27 UTC, henkbirkholz commented on examples/feed-basic-example.md
> +To demonstrate how SCITT Implements this workflow a collection of Scenarios and examples are provided using the [SCITT Community API Emulator](https://github.com/scitt-community/scitt-api-emulator) a
also caps in scenario

2023-10-09 14:29 UTC, henkbirkholz commented on examples/feed-basic-example.md
> +Put simply, a Feed represents a specific Artifact, with a series of statements placed on the Feed.
This is a thesis that we should cross check on the list, right?

2023-10-09 14:33 UTC, henkbirkholz commented on examples/feed-basic-example.md
> +## Scenario: Series of Transparent Statements Over the Life of an Artifact
Is this scenarios related to https://www.ietf.org/archive/id/draft-ietf-scitt-software-use-cases-01.html#name-security-analysis-of-a-soft? If so, what are the differences?

2023-10-09 14:38 UTC, henkbirkholz commented on examples/feed-basic-example.md
> +- A Feed should be owned by the issuer of the artifact
Maybe:

```suggestion
- A Feed should is defined by the issuer of the artifact
```

2023-10-09 14:39 UTC, henkbirkholz commented on examples/feed-basic-example.md
> +- Other parties may reference the same Feed, making additional statements, signed with their identity
```suggestion
- Other parties can reference the same Feed, making additional statements, signed with their identity
```

2023-10-09 14:39 UTC, henkbirkholz commented on examples/feed-basic-example.md
> +  - Other parties, if permitted by the registration policy of the publishers SCITT instance, may publish Signed Statements to the same Feed
```suggestion
  - Other parties, if permitted by the registration policy of the publishers SCITT instance, can publish Signed Statements to the same Feed
```

2023-10-09 14:39 UTC, henkbirkholz commented on examples/feed-basic-example.md
> +  - To enable autonomy, other parties may publish Signed Statements to a different SCITT instance, about the same Feed
```suggestion
  - To enable autonomy, other parties can publish Signed Statements to a different SCITT instance, about the same Feed
```

2023-10-09 16:35 UTC, OR13 requested changes
@SteveLasker please merge or dismiss @henkbirkholz 's suggestions, then I will approve again.

2023-10-09 17:13 UTC, SteveLasker commented on examples/feed-basic-example.md
> +Put simply, a Feed represents a specific Artifact, with a series of statements placed on the Feed.
From [3. Terminology: feed](https://www.ietf.org/archive/id/draft-ietf-scitt-architecture-02.html#section-3-2.10.1)
> an identifier chosen by the Issuer for the Artifact. For every Issuer and Feed, the Registry on a Transparency Service contains a sequence of Signed Statements about the same Artifact. In COSE, Feed is a dedicated header attribute in the protected header of the Envelope.

We have open PRs to clarify how a feed accomplishes this task, but do we think this is different?

2023-10-09 17:25 UTC, SteveLasker commented on examples/feed-basic-example.md
> +## Scenario: Series of Transparent Statements Over the Life of an Artifact
I'd suggest this is a more detailed explanation of the usecase, consistent with our goals from the [Charter](https://datatracker.ietf.org/wg/scitt/about/), as captured here: [Architectural Model: Actors, Interactions, Terminology](https://datatracker.ietf.org/wg/scitt/about/#architectural-model-actors-interactions-terminology)

If we like this level of detail, I can PR it back to the use case document. 
Shall we iterate here, and then PR back? Or, move this PR back to the [use-case repo](https://github.com/ietf-wg-scitt/draft-ietf-scitt-software-use-cases)?

2023-10-09 17:28 UTC, SteveLasker commented
> @SteveLasker please merge or dismiss @henkbirkholz 's suggestions, then I will approve again.

Thanks, @OR13, merged the actionable ones, and replied to the questions.

2023-10-09 17:52 UTC, OR13 commented on examples/feed-basic-example.md
> +## Scenario: Series of Transparent Statements Over the Life of an Artifact
`draft-ietf-scitt-software-use-cases` is a WG adopted document, this is a community blog.

You need WG consensus to update WG adopted items, the blog can be updated by the people who control the website.

I suggest resolving this comment thread and taking no action.

2023-10-09 17:53 UTC, OR13 commented on examples/feed-basic-example.md
> +Put simply, a Feed represents a specific Artifact, with a series of statements placed on the Feed.
This community website does not reflect IETF consensus.

This thread should be resolved.

2023-10-09 17:55 UTC, OR13 requested changes
I reviewed again, there seems to be confusion regarding mangement of this repo, vs iETF work items, code owners have the ability to merge PRs here, IETF consenus is not required.

I'd like to see mandatory reviews from code owners, and I will approve after all threads are marked resolved.

2023-10-09 18:47 UTC, OR13 approved these changes

2023-10-09 18:50 UTC, OR13 commented on examples/feed-basic-example.md
> +## Scenario: Series of Transparent Statements Over the Life of an Artifact
Continue discussion on https://github.com/scitt-community/scitt-web/issues/43

2023-10-09 18:53 UTC, SteveLasker commented
> I reviewed again, there seems to be confusion regarding mangement of this repo, vs iETF work items, code owners have the ability to merge PRs here, IETF consenus is not required.

Correct, this is the SCITT Community, which supports the IETF SCITT specs, but is a more diverse group. 
See [SCITT Community](https://github.com/scitt-community#overview)

2023-10-09 22:23 UTC, merged